### ISSUE TITLE
sshfs with macfuse doesn't work on BigSur 11.3.1

### ISSUE THREAD

**Issue by eliselucotte** [osxfuse/osxfuse#811]
Hi, 
I am aware that this issue was previously raised, but the solutions did not work for me.
Big Sur 11.3.1
sshfs 2.5 
macfuse 4.1 (both downloaded from https://osxfuse.github.io/)

When I used sshfs to mount a distant server, I get this error:
```
mount_macfuse: failed to mount server@/dev/macfuse0: Operation not permitted
fuse: mount failed with errro: 1
```
I also tried to install sshfs using brew 
```
brew install gromgit/fuse/sshfs
```
And I get the following error when it gets to the "make install" step:
```
sshfs.c:15:10: fatal error: 'fuse_lowlevel.h' file not found
```
Any idea how to fix it ? I can mount this server fine using my personal mac that runs on an older version of mac.
Thanks in advances !

**Comment by bfleischer** [comment]
The sshfs 2.5.0 release from https://osxfuse.github.io worked fine in my tests on Big Sur. Could you please post your sshfs command? The "Operation not permitted" error could mean that there is something wrong with the way you call sshfs.

**Comment by eliselucotte** [comment]
Thanks for the quick reply !
Here is my command:
```
sudo mkdir -p /Users/eliselucotte/Desktop/server1
sudo chown -R $eliselucotte:staff /Users/eliselucotte/Desktop/server1
sshfs $elise@129.175.107.244:/home/elise /Users/eliselucotte/Desktop/server1

```
It does the same without the sudo chown command.
The same command works for Sierra 10.12.6.

**Comment by bfleischer** [comment]
You don't need sudo. The following commands work fine for me:

```
% mkdir /Users/benjamin/Desktop/mount
% sshfs benjamin@10.236.0.130:/Users/benjamin/Desktop/test /Users/benjamin/Desktop/mount
```

Why are you using `$eliselucotte` and `$elise`? The shell will interpret both as variables. Can you make sure that /Users/eliselucotte/Desktop/server1 is actually owned by the user that is running the sshfs command?

**Comment by eliselucotte** [comment]
I just removed the sudo before the mkdir and it works ! THANK YOU ! I've been working on this for hours !!
Actually the $elise was a copy paste mistake (I used a variable uname=elise, and then $uname within the command line).
Thank you again !
